[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
universal_game = "BELsmsp7jdUSUJDfcsLXP8HSdJsaAtbSBSJ95gRUbTyg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-keypair.json"

[workspace]
members = ["programs/universal-game"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
