[workspace]
members = [
    "programs/universal-game"
]
exclude = [
    "programs/target"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
overflow-checks = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

